import {
	RegistrationId, UniOHLPushCallback, UniOHLPushReceiver, AddPushReceiver, StopPush, RestartPush,
	IsPushStopped, SetAlias, GetAlias, DeleteAlias, AddTags, GetTags, DeleteTags, CleanTags, SetShowBadge,
	GetShowBadge, SetSilenceTime, GetDeviceToken, IsNotificationsEnabled, RegisterDeviceToken, SetupUserLanguage
} from '../interface.uts'
import OHLPush from 'com.ohaola.sdk.push.OHLPush';
import OHLPUSH from 'com.ohaola.commons.OHLPUSH';
import OHLPushCustomMessage from 'com.ohaola.sdk.push.OHLPushCustomMessage';
import OHLPushNotifyMessage from 'com.ohaola.sdk.push.OHLPushNotifyMessage';
import OHLPushReceiver from 'com.ohaola.sdk.push.OHLPushReceiver';
import Context from 'android.content.Context';
import KotlinArray from 'kotlin.Array';
import OHLPushCallback from 'com.ohaola.sdk.push.OHLPushCallback';
import MobSDK from 'com.mob.MobSDK'
import HashonHelper from 'com.mob.tools.utils.HashonHelper';
import Application from "android.app.Application";
import Activity from "android.app.Activity";
import Bundle from "android.os.Bundle";
import ActivityLifecycleCallbacks from 'android.app.Application.ActivityLifecycleCallbacks';

let hasAddChannel = false
let uniReceiver : UniOHLPushReceiver | null = null
let cachedClickEvents : Array<string> = []

export const getRegistrationID : RegistrationId = function (callback : UniOHLPushCallback) {
	setChannel()
	OHLPush.getRegistrationId(new unicallback<String>(callback))
}
@UTSJS.keepAlive
export function addPushReceiver(receiver : UniOHLPushReceiver) {
	setChannel()
	if (cachedClickEvents.length > 0) {
		cachedClickEvents.forEach((msg) => {
			receiver.onNotifyMessageOpenedReceive(msg)
		})
		cachedClickEvents = []
	}
	uniReceiver = receiver
}

export const stopPush : StopPush = function () : void {
	setChannel()
	OHLPush.stopPush();
}


export const restartPush : RestartPush = function () : void {
	setChannel()
	OHLPush.restartPush();
}


export const isPushStopped : IsPushStopped = function (callback : UniOHLPushCallback) {
	setChannel()
	OHLPush.isPushStopped(new unicallback<Boolean>(callback))
}

export const setAlias : SetAlias = function (alias : string) : void {
	setChannel()
	OHLPush.setAlias(alias)
}

export const getAlias : GetAlias = function () : void {
	setChannel()
	OHLPush.getAlias()
}

export const deleteAlias : DeleteAlias = function () : void {
	setChannel()
	OHLPush.deleteAlias()
}


export const addTags : AddTags = function (tags : string[]) : void {
	setChannel()
	OHLPush.addTags(tags.toTypedArray())
}

export const getTags : GetTags = function () : void {
	setChannel()
	OHLPush.getTags()
}

export const deleteTags : DeleteTags = function (tags : string[]) : void {
	setChannel()
	OHLPush.deleteTags(tags.toTypedArray())
}


export const cleanTags : CleanTags = function () : void {
	setChannel()
	OHLPush.cleanTags()
}

export const setShowBadge : SetShowBadge = function (isShow : boolean) : void {
	setChannel()
	OHLPush.setShowBadge(isShow)
}

export const getShowBadge : GetShowBadge = function (callback : UniOHLPushCallback) {
	setChannel()
	OHLPush.getShowBadge(new unicallback<Boolean>(callback))
}

export const setSilenceTime : SetSilenceTime = function (startHour : Int, startMinute : Int, endHour : Int, endMinute : Int) : void {
	setChannel()
	OHLPush.setSilenceTime(startHour, startMinute, endHour, endMinute)
}

export const registerDeviceToken : RegisterDeviceToken = function (channel : string, token : string) {
	setChannel()
	OHLPush.setDeviceTokenByUser(channel, token)
}

export const setupUserLanguage : SetupUserLanguage = function (language : string) {
	setChannel()
	OHLPush.setUserLanguage(language)
}

export const getDeviceToken : GetDeviceToken = function (callback : UniOHLPushCallback) {
	setChannel()
	OHLPush.getDeviceToken(new unicallback<String>(callback))
} 

export const isNotificationsEnabled : IsNotificationsEnabled = function (callback : UniOHLPushCallback) {
	setChannel()
	OHLPush.isNotificationsEnabled(new unicallback<Boolean>(callback))
} 

function setChannel() {
	if (!hasAddChannel) {
		UTSAndroid.getDispatcher("io").async(function (_) {
			MobSDK.setChannel(new OHLPUSH(), MobSDK.CHANNEL_UNIAPP);
		}, null)
		hasAddChannel = true
	}
}

class unicallback<T> implements OHLPushCallback<T> {
	jsCallback : UniOHLPushCallback

	constructor(callback : UniOHLPushCallback) {
		super();
		this.jsCallback = callback
	}

	override onCallback(data : T) : void {
		let result : UTSJSONObject = {
			"success": true,
			"res": data as any,
			"error": null
		}
		this.jsCallback.onCallback(result)
	}
}

class innerReceiver implements OHLPushReceiver {

	override  onCustomMessageReceive(context : Context, mobPushCustomMessage : OHLPushCustomMessage) : void {
		const receiver = uniReceiver;
		if (receiver != null) {
			receiver.onCustomMessageReceive(HashonHelper.fromObject(mobPushCustomMessage))
		}
	}

	override  onNotifyMessageReceive(context : Context, mobPushNotifyMessage : OHLPushNotifyMessage) : void {
		const receiver = uniReceiver;
		if (receiver != null) {
			receiver.onNotifyMessageReceive(HashonHelper.fromObject(mobPushNotifyMessage))
		}
	}


	override  onNotifyMessageOpenedReceive(context : Context, mobPushNotifyMessage : OHLPushNotifyMessage) : void {
		let msg = HashonHelper.fromObject(mobPushNotifyMessage)
		const receiver = uniReceiver;
		if (receiver != null) {
			receiver.onNotifyMessageOpenedReceive(msg)
		} else {
			cachedClickEvents.push(msg)
		}
	}

	override onTagsCallback(context : Context, tags ?: KotlinArray<string>, operation : Int, errorCode : Int) : void {
		if (tags == null) {
			tags = arrayOf("")
		}
		const receiver = uniReceiver;
		if (receiver != null) {
			receiver.onTagsCallback(Array.fromNative(tags), operation, errorCode)
		}
	}

	override onAliasCallback(context : Context, alias ?: String, operation : Int, errorCode : Int) : void {
		if(alias == null){
			alias = ""
		}
		const receiver = uniReceiver;
		if (receiver != null) {
			receiver.onAliasCallback(alias, operation, errorCode)
		}
	}
}

export class AppHookProxy implements UTSAndroidHookProxy {
	override onCreate(application : Application) {
		addInnerReceiver(application)
	}
}

@UTSJS.keepAlive
function addInnerReceiver(application : Application) {
	OHLPush.addPushReceiver(new innerReceiver())
	application.registerActivityLifecycleCallbacks(new MyLifecycleCallbacks())
}


class MyLifecycleCallbacks implements ActivityLifecycleCallbacks {
	override onActivityCreated(a : Activity, b : Bundle | null) : void {
		OHLPush.parseManufacturerMessage(a.getIntent())
	}

	override onActivityStarted(a : Activity) : void {

	}

	override onActivityResumed(a : Activity) : void {

	}

	override onActivityPaused(a : Activity) : void {

	}

	override onActivityStopped(a : Activity) : void {

	}

	override onActivitySaveInstanceState(a : Activity, b : Bundle) : void {

	}

	override onActivityDestroyed(a : Activity) : void {

	}

}